"""Tests for compute_risk_score() — pure unit tests with synthetic inputs only."""

from __future__ import annotations

import pytest

from backend.signals.fraud_signal import compute_risk_score


# ---------------------------------------------------------------------------
# Helpers to build synthetic claim dicts
# ---------------------------------------------------------------------------

def _skill_claim(name: str, evidence_level: str) -> dict:
    return {"claim": name, "type": "skill", "evidence_level": evidence_level}


def _consistency_finding(claim: str, status: str) -> dict:
    return {"claim": claim, "status": status}


# ---------------------------------------------------------------------------
# No risk
# ---------------------------------------------------------------------------

def test_no_risk() -> None:
    """All signals clean → risk_score == 0."""
    score = compute_risk_score(
        compatibility=85,
        inflated_claims=[
            _skill_claim("Python", "demonstrated"),
            _skill_claim("Docker", "supported"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["implemented", "deployed"],
        consistency_findings=[],
        strictness="medium",
        cross_reference_sync=True,
    )
    assert score == 0


# ---------------------------------------------------------------------------
# Low risk
# ---------------------------------------------------------------------------

def test_low_risk() -> None:
    """A few inflated claims but low strictness keeps risk low."""
    score = compute_risk_score(
        compatibility=70,
        inflated_claims=[
            _skill_claim("Kubernetes", "inflated"),
            _skill_claim("Terraform", "inflated"),
        ],
        missing_skills_raw=["AWS", "Docker"],
        action_verbs_list=["built", "deployed"],
        consistency_findings=[],
        strictness="low",
        cross_reference_sync=True,
    )
    # low strictness → inflated_penalty=8 → 2 * 8 = 16
    assert 0 < score <= 30


# ---------------------------------------------------------------------------
# Medium risk
# ---------------------------------------------------------------------------

def test_medium_risk() -> None:
    """Several inflated skill claims at medium strictness → moderate risk."""
    score = compute_risk_score(
        compatibility=60,
        inflated_claims=[
            _skill_claim("Kubernetes", "inflated"),
            _skill_claim("Terraform", "inflated"),
            _skill_claim("Docker", "inflated"),
            _skill_claim("AWS", "inflated"),
        ],
        missing_skills_raw=["Java", "C++"],
        action_verbs_list=["built"],
        consistency_findings=[],
        strictness="medium",
        cross_reference_sync=True,
    )
    # medium strictness → inflated_penalty=14 → 4 * 14 = 56
    assert 50 <= score <= 60


# ---------------------------------------------------------------------------
# High risk
# ---------------------------------------------------------------------------

def test_high_risk() -> None:
    """Many inflated skill claims at high strictness → risk near cap."""
    score = compute_risk_score(
        compatibility=30,
        inflated_claims=[
            _skill_claim("Kubernetes", "inflated"),
            _skill_claim("Terraform", "inflated"),
            _skill_claim("Docker", "inflated"),
            _skill_claim("AWS", "inflated"),
            _skill_claim("Jenkins", "inflated"),
        ],
        missing_skills_raw=["Java", "C++", "Go", "Rust"],
        action_verbs_list=[],
        consistency_findings=[],
        strictness="high",
        cross_reference_sync=True,
    )
    # high strictness → inflated_penalty=24 → 5 * 24 = 120 → capped at 100
    # plus no action verbs → +10 → still capped at 100
    assert score == 100


# ---------------------------------------------------------------------------
# Duplicate inflated claims (same skill listed multiple times)
# ---------------------------------------------------------------------------

def test_duplicate_inflated_claims() -> None:
    """Duplicate inflated claims for the same skill should each count."""
    score = compute_risk_score(
        compatibility=70,
        inflated_claims=[
            _skill_claim("Kubernetes", "inflated"),
            _skill_claim("Kubernetes", "inflated"),
            _skill_claim("Kubernetes", "inflated"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[],
        strictness="medium",
        cross_reference_sync=True,
    )
    # medium → inflated_penalty=14 → 3 * 14 = 42
    assert score == 42


# ---------------------------------------------------------------------------
# Capped penalties
# ---------------------------------------------------------------------------

def test_capped_penalties() -> None:
    """Cross-reference penalty is capped at 40 regardless of how many findings."""
    score = compute_risk_score(
        compatibility=50,
        inflated_claims=[],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
            _consistency_finding("expert level", "buzzword"),
        ],
        missing_skills_raw=[],
        action_verbs_list=["built"],
        consistency_findings=[
            _consistency_finding("expert in everything", "buzzword"),
            _consistency_finding("ninja coder", "buzzword"),
            _consistency_finding("guru level", "buzzword"),
            _consistency_finding("rockstar dev", "buzzword"),
            _consistency_finding("thought leader", "buzzword"),
            _consistency_finding("world class", "buzzword"),
            _consistency_finding("passionate about", "buzzword"),
            _consistency_finding("cutting edge", "buzzword"),
            _consistency_finding("proficient", "buzzword"),
